url: "https://human-factors-lab.github.io"
baseurl: ""
title: "OU HFS Lab"
encoding: utf-8

# Disable the default primer theme from github-pages
theme: null

collections:
  programs:
    output: false
  members:
    output: false
  projects:
    output: true
    permalink: /research/:name/

defaults:
  -
    scope:
      path: ""
    values:
      layout: single
      header:
        background-image: /assets/img/ouhfs/home/scanpathtower.jpg
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: projects
    values:
      layout: project
      header:
        background-image: /assets/img/ouhfs/home/scanpathtower.jpg

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
